#!/usr/bin/env bash
# One-time setup for a stable Cloudflare Named Tunnel (permanent API URL).
#
# Requires:
#   - free Cloudflare account (cloudflared tunnel login)
#   - a domain on Cloudflare DNS (e.g. api.yourdomain.com)
#
# Usage:
#   ./scripts/setup-named-tunnel.sh api.yourdomain.com
#   RUDRA_TUNNEL_HOSTNAME=api.yourdomain.com ./scripts/setup-named-tunnel.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

HOSTNAME="${1:-${RUDRA_TUNNEL_HOSTNAME:-}}"
TUNNEL_NAME="${RUDRA_TUNNEL_NAME:-rudra}"
PORT="${RUDRA_BACKEND_PORT:-8000}"
CF_DIR="$ROOT/infrastructure/cloudflared"
CONFIG="$CF_DIR/config.yml"
CERT="$HOME/.cloudflared/cert.pem"

say() { printf "\033[1;36m→ %s\033[0m\n" "$1"; }
ok()  { printf "\033[1;32m✓ %s\033[0m\n" "$1"; }
err() { printf "\033[1;31m✗ %s\033[0m\n" "$1"; }

command -v cloudflared >/dev/null 2>&1 || { err "Install cloudflared: brew install cloudflared"; exit 1; }

if [ -z "$HOSTNAME" ]; then
  err "Hostname required."
  echo ""
  echo "You need a domain on Cloudflare DNS (free account + any domain you own)."
  echo "  1. Sign up: https://dash.cloudflare.com/sign-up"
  echo "  2. Add your domain (or register one in Cloudflare Registrar)"
  echo "  3. Re-run:  ./scripts/setup-named-tunnel.sh api.yourdomain.com"
  echo ""
  echo "Pick a subdomain for the backend, e.g. api.yourdomain.com"
  exit 1
fi

PUBLIC_URL="https://${HOSTNAME}"

if [ ! -f "$CERT" ]; then
  say "Logging in to Cloudflare (opens browser)..."
  cloudflared tunnel login
fi

if [ ! -f "$CERT" ]; then
  err "Login failed — cert.pem not found at $CERT"
  exit 1
fi
ok "Cloudflare login OK"

mkdir -p "$CF_DIR"

if ! cloudflared tunnel list 2>/dev/null | awk 'NR>1 {print $2}' | grep -qx "$TUNNEL_NAME"; then
  say "Creating tunnel '$TUNNEL_NAME'..."
  cloudflared tunnel create "$TUNNEL_NAME"
else
  say "Tunnel '$TUNNEL_NAME' already exists."
fi

TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" 'NR>1 && $2==n {print $1; exit}')"

CREDS="$HOME/.cloudflared/${TUNNEL_ID}.json"
if [ ! -f "$CREDS" ]; then
  err "Credentials file not found: $CREDS"
  exit 1
fi

say "Routing DNS: $HOSTNAME → tunnel $TUNNEL_NAME"
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME"

cat > "$CONFIG" <<EOF
# Generated by setup-named-tunnel.sh — do not commit (gitignored).
tunnel: $TUNNEL_ID
credentials-file: $CREDS

ingress:
  - hostname: $HOSTNAME
    service: http://localhost:$PORT
  - service: http_status:404
EOF

mkdir -p "$ROOT/.run"
printf '%s\n' "$PUBLIC_URL" > "$ROOT/.run/tunnel-url.txt"

# Persist hostname in root .env for scripts (append if missing).
if [ -f "$ROOT/.env" ]; then
  grep -q '^RUDRA_TUNNEL_HOSTNAME=' "$ROOT/.env" 2>/dev/null \
    && sed -i '' "s|^RUDRA_TUNNEL_HOSTNAME=.*|RUDRA_TUNNEL_HOSTNAME=$HOSTNAME|" "$ROOT/.env" \
    || echo "RUDRA_TUNNEL_HOSTNAME=$HOSTNAME" >> "$ROOT/.env"
  grep -q '^RUDRA_PUBLIC_API_URL=' "$ROOT/.env" 2>/dev/null \
    && sed -i '' "s|^RUDRA_PUBLIC_API_URL=.*|RUDRA_PUBLIC_API_URL=$PUBLIC_URL|" "$ROOT/.env" \
    || echo "RUDRA_PUBLIC_API_URL=$PUBLIC_URL" >> "$ROOT/.env"
fi

echo ""
ok "Named tunnel configured"
echo "   Hostname:    $HOSTNAME"
echo "   Public API:  $PUBLIC_URL"
echo "   Config:      $CONFIG"
echo ""
echo "Next:"
echo "   ./scripts/start-named-tunnel.sh"
echo "   ./scripts/sync-vercel-backend.sh"
